### ISSUE TITLE
GLTFLoader isn't exported by three@0.112.0

### ISSUE THREAD

**Issue by rohan-deshpande** [johh/three-gltf-loader#8]
In the docs it says that this is exported by three from `v0.111.0` but it's not there in `v0.112.0` it's not exported by the package at all so I think your lib is still useful.

**Comment by rohan-deshpande** [comment]
Just saw this `import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader';` I will close

**Comment by rohan-deshpande** [comment]
Hmm, no I am reopening because doing this causes an error as the loader file uses import syntax

`SyntaxError: Cannot use import statement outside a module`

**Comment by johh** [comment]
Hey there! Starting with `v0.103.0` the `three` package includes `GLTFLoader` both as a module (`three/examples/jsm/loaders/GLTFLoader`) and as a directly browser compatible version (`three/examples/js/loaders/GLTFLoader.js`).
Depending on your setup, you need to either import the module `import { GLTFLoader } from ...` or include the browser version in your HTML, which exposes the loader as `THREE.GLTFLoader`.

Hope that cleared things up a bit. If you have any more problems, I'd be happy to help.

Closing, since this isn't directly related to the `three-gltf-loader` package.

**Comment by rohan-deshpande** [comment]
I’m curious as to how you are getting it working with webpack or parcel importing directly from the examples in three. I’ve had to use your package. Any chance you can share your config?
